/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsCreateRouteImport } from './routes/events.create'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as AuthParticipantRouteImport } from './routes/auth.participant'
import { Route as AuthJudgeRouteImport } from './routes/auth.judge'
import { Route as AuthHostRouteImport } from './routes/auth.host'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthAttenderRouteImport } from './routes/auth.attender'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardParticipantRouteImport } from './routes/_authenticated/dashboard.participant'
import { Route as AuthenticatedDashboardJudgeRouteImport } from './routes/_authenticated/dashboard.judge'
import { Route as AuthenticatedDashboardHostRouteImport } from './routes/_authenticated/dashboard.host'
import { Route as AuthenticatedDashboardAttenderRouteImport } from './routes/_authenticated/dashboard.attender'
import { Route as AuthenticatedDashboardAttenderIndexRouteImport } from './routes/_authenticated/dashboard.attender.index'
import { Route as AuthenticatedEventSlugSubmitRouteImport } from './routes/_authenticated/event.$slug.submit'
import { Route as AuthenticatedDashboardHostGuideRouteImport } from './routes/_authenticated/dashboard.host.guide'
import { Route as AuthenticatedDashboardAttenderScanRouteImport } from './routes/_authenticated/dashboard.attender.scan'
import { Route as AuthenticatedDashboardAttenderHistoryRouteImport } from './routes/_authenticated/dashboard.attender.history'
import { Route as AuthenticatedEventSlugFormRegisterRouteImport } from './routes/_authenticated/event.$slug.form.register'
import { Route as AuthenticatedDashboardHostEventsIdRouteImport } from './routes/_authenticated/dashboard.host.events.$id'
import { Route as AuthenticatedDashboardHostEventsIdIndexRouteImport } from './routes/_authenticated/dashboard.host.events.$id.index'
import { Route as AuthenticatedDashboardParticipantEventsEventIdTeamRouteImport } from './routes/_authenticated/dashboard.participant.events.$eventId.team'
import { Route as AuthenticatedDashboardParticipantEventsEventIdSubmissionsRouteImport } from './routes/_authenticated/dashboard.participant.events.$eventId.submissions'
import { Route as AuthenticatedDashboardParticipantEventsEventIdScheduleRouteImport } from './routes/_authenticated/dashboard.participant.events.$eventId.schedule'
import { Route as AuthenticatedDashboardParticipantEventsEventIdInfoRouteImport } from './routes/_authenticated/dashboard.participant.events.$eventId.info'
import { Route as AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRouteImport } from './routes/_authenticated/dashboard.participant.events.$eventId.announcements'
import { Route as AuthenticatedDashboardJudgeEventsEventIdScheduleRouteImport } from './routes/_authenticated/dashboard.judge.events.$eventId.schedule'
import { Route as AuthenticatedDashboardHostEventsIdWebsiteRouteImport } from './routes/_authenticated/dashboard.host.events.$id.website'
import { Route as AuthenticatedDashboardHostEventsIdSubmissionsRouteImport } from './routes/_authenticated/dashboard.host.events.$id.submissions'
import { Route as AuthenticatedDashboardHostEventsIdSettingsRouteImport } from './routes/_authenticated/dashboard.host.events.$id.settings'
import { Route as AuthenticatedDashboardHostEventsIdScoresRouteImport } from './routes/_authenticated/dashboard.host.events.$id.scores'
import { Route as AuthenticatedDashboardHostEventsIdScheduleRouteImport } from './routes/_authenticated/dashboard.host.events.$id.schedule'
import { Route as AuthenticatedDashboardHostEventsIdRegistrationsRouteImport } from './routes/_authenticated/dashboard.host.events.$id.registrations'
import { Route as AuthenticatedDashboardHostEventsIdJudgesRouteImport } from './routes/_authenticated/dashboard.host.events.$id.judges'
import { Route as AuthenticatedDashboardHostEventsIdFormRouteImport } from './routes/_authenticated/dashboard.host.events.$id.form'
import { Route as AuthenticatedDashboardHostEventsIdAttendersRouteImport } from './routes/_authenticated/dashboard.host.events.$id.attenders'
import { Route as AuthenticatedDashboardHostEventsIdAnnouncementsRouteImport } from './routes/_authenticated/dashboard.host.events.$id.announcements'
import { Route as AuthenticatedDashboardHostEventsIdAnalyticsRouteImport } from './routes/_authenticated/dashboard.host.events.$id.analytics'
import { Route as AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRouteImport } from './routes/_authenticated/dashboard.judge.events.$eventId.submissions.$submissionId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthParticipantRoute = AuthParticipantRouteImport.update({
  id: '/auth/participant',
  path: '/auth/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJudgeRoute = AuthJudgeRouteImport.update({
  id: '/auth/judge',
  path: '/auth/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHostRoute = AuthHostRouteImport.update({
  id: '/auth/host',
  path: '/auth/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAttenderRoute = AuthAttenderRouteImport.update({
  id: '/auth/attender',
  path: '/auth/attender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardParticipantRoute =
  AuthenticatedDashboardParticipantRouteImport.update({
    id: '/dashboard/participant',
    path: '/dashboard/participant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardJudgeRoute =
  AuthenticatedDashboardJudgeRouteImport.update({
    id: '/dashboard/judge',
    path: '/dashboard/judge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHostRoute =
  AuthenticatedDashboardHostRouteImport.update({
    id: '/dashboard/host',
    path: '/dashboard/host',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAttenderRoute =
  AuthenticatedDashboardAttenderRouteImport.update({
    id: '/dashboard/attender',
    path: '/dashboard/attender',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAttenderIndexRoute =
  AuthenticatedDashboardAttenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAttenderRoute,
  } as any)
const AuthenticatedEventSlugSubmitRoute =
  AuthenticatedEventSlugSubmitRouteImport.update({
    id: '/event/$slug/submit',
    path: '/event/$slug/submit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHostGuideRoute =
  AuthenticatedDashboardHostGuideRouteImport.update({
    id: '/guide',
    path: '/guide',
    getParentRoute: () => AuthenticatedDashboardHostRoute,
  } as any)
const AuthenticatedDashboardAttenderScanRoute =
  AuthenticatedDashboardAttenderScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedDashboardAttenderRoute,
  } as any)
const AuthenticatedDashboardAttenderHistoryRoute =
  AuthenticatedDashboardAttenderHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardAttenderRoute,
  } as any)
const AuthenticatedEventSlugFormRegisterRoute =
  AuthenticatedEventSlugFormRegisterRouteImport.update({
    id: '/event/$slug/form/register',
    path: '/event/$slug/form/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdRoute =
  AuthenticatedDashboardHostEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedDashboardHostRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdIndexRoute =
  AuthenticatedDashboardHostEventsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardParticipantEventsEventIdTeamRoute =
  AuthenticatedDashboardParticipantEventsEventIdTeamRouteImport.update({
    id: '/events/$eventId/team',
    path: '/events/$eventId/team',
    getParentRoute: () => AuthenticatedDashboardParticipantRoute,
  } as any)
const AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute =
  AuthenticatedDashboardParticipantEventsEventIdSubmissionsRouteImport.update({
    id: '/events/$eventId/submissions',
    path: '/events/$eventId/submissions',
    getParentRoute: () => AuthenticatedDashboardParticipantRoute,
  } as any)
const AuthenticatedDashboardParticipantEventsEventIdScheduleRoute =
  AuthenticatedDashboardParticipantEventsEventIdScheduleRouteImport.update({
    id: '/events/$eventId/schedule',
    path: '/events/$eventId/schedule',
    getParentRoute: () => AuthenticatedDashboardParticipantRoute,
  } as any)
const AuthenticatedDashboardParticipantEventsEventIdInfoRoute =
  AuthenticatedDashboardParticipantEventsEventIdInfoRouteImport.update({
    id: '/events/$eventId/info',
    path: '/events/$eventId/info',
    getParentRoute: () => AuthenticatedDashboardParticipantRoute,
  } as any)
const AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute =
  AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRouteImport.update(
    {
      id: '/events/$eventId/announcements',
      path: '/events/$eventId/announcements',
      getParentRoute: () => AuthenticatedDashboardParticipantRoute,
    } as any,
  )
const AuthenticatedDashboardJudgeEventsEventIdScheduleRoute =
  AuthenticatedDashboardJudgeEventsEventIdScheduleRouteImport.update({
    id: '/events/$eventId/schedule',
    path: '/events/$eventId/schedule',
    getParentRoute: () => AuthenticatedDashboardJudgeRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdWebsiteRoute =
  AuthenticatedDashboardHostEventsIdWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdSubmissionsRoute =
  AuthenticatedDashboardHostEventsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdSettingsRoute =
  AuthenticatedDashboardHostEventsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdScoresRoute =
  AuthenticatedDashboardHostEventsIdScoresRouteImport.update({
    id: '/scores',
    path: '/scores',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdScheduleRoute =
  AuthenticatedDashboardHostEventsIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdRegistrationsRoute =
  AuthenticatedDashboardHostEventsIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdJudgesRoute =
  AuthenticatedDashboardHostEventsIdJudgesRouteImport.update({
    id: '/judges',
    path: '/judges',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdFormRoute =
  AuthenticatedDashboardHostEventsIdFormRouteImport.update({
    id: '/form',
    path: '/form',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdAttendersRoute =
  AuthenticatedDashboardHostEventsIdAttendersRouteImport.update({
    id: '/attenders',
    path: '/attenders',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdAnnouncementsRoute =
  AuthenticatedDashboardHostEventsIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardHostEventsIdAnalyticsRoute =
  AuthenticatedDashboardHostEventsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardHostEventsIdRoute,
  } as any)
const AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute =
  AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRouteImport.update(
    {
      id: '/events/$eventId/submissions/$submissionId',
      path: '/events/$eventId/submissions/$submissionId',
      getParentRoute: () => AuthenticatedDashboardJudgeRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/attender': typeof AuthAttenderRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/host': typeof AuthHostRoute
  '/auth/judge': typeof AuthJudgeRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/event/$slug': typeof EventSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/attender': typeof AuthenticatedDashboardAttenderRouteWithChildren
  '/dashboard/host': typeof AuthenticatedDashboardHostRouteWithChildren
  '/dashboard/judge': typeof AuthenticatedDashboardJudgeRouteWithChildren
  '/dashboard/participant': typeof AuthenticatedDashboardParticipantRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/attender/history': typeof AuthenticatedDashboardAttenderHistoryRoute
  '/dashboard/attender/scan': typeof AuthenticatedDashboardAttenderScanRoute
  '/dashboard/host/guide': typeof AuthenticatedDashboardHostGuideRoute
  '/event/$slug/submit': typeof AuthenticatedEventSlugSubmitRoute
  '/dashboard/attender/': typeof AuthenticatedDashboardAttenderIndexRoute
  '/dashboard/host/events/$id': typeof AuthenticatedDashboardHostEventsIdRouteWithChildren
  '/event/$slug/form/register': typeof AuthenticatedEventSlugFormRegisterRoute
  '/dashboard/host/events/$id/analytics': typeof AuthenticatedDashboardHostEventsIdAnalyticsRoute
  '/dashboard/host/events/$id/announcements': typeof AuthenticatedDashboardHostEventsIdAnnouncementsRoute
  '/dashboard/host/events/$id/attenders': typeof AuthenticatedDashboardHostEventsIdAttendersRoute
  '/dashboard/host/events/$id/form': typeof AuthenticatedDashboardHostEventsIdFormRoute
  '/dashboard/host/events/$id/judges': typeof AuthenticatedDashboardHostEventsIdJudgesRoute
  '/dashboard/host/events/$id/registrations': typeof AuthenticatedDashboardHostEventsIdRegistrationsRoute
  '/dashboard/host/events/$id/schedule': typeof AuthenticatedDashboardHostEventsIdScheduleRoute
  '/dashboard/host/events/$id/scores': typeof AuthenticatedDashboardHostEventsIdScoresRoute
  '/dashboard/host/events/$id/settings': typeof AuthenticatedDashboardHostEventsIdSettingsRoute
  '/dashboard/host/events/$id/submissions': typeof AuthenticatedDashboardHostEventsIdSubmissionsRoute
  '/dashboard/host/events/$id/website': typeof AuthenticatedDashboardHostEventsIdWebsiteRoute
  '/dashboard/judge/events/$eventId/schedule': typeof AuthenticatedDashboardJudgeEventsEventIdScheduleRoute
  '/dashboard/participant/events/$eventId/announcements': typeof AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute
  '/dashboard/participant/events/$eventId/info': typeof AuthenticatedDashboardParticipantEventsEventIdInfoRoute
  '/dashboard/participant/events/$eventId/schedule': typeof AuthenticatedDashboardParticipantEventsEventIdScheduleRoute
  '/dashboard/participant/events/$eventId/submissions': typeof AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute
  '/dashboard/participant/events/$eventId/team': typeof AuthenticatedDashboardParticipantEventsEventIdTeamRoute
  '/dashboard/host/events/$id/': typeof AuthenticatedDashboardHostEventsIdIndexRoute
  '/dashboard/judge/events/$eventId/submissions/$submissionId': typeof AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/attender': typeof AuthAttenderRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/host': typeof AuthHostRoute
  '/auth/judge': typeof AuthJudgeRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/event/$slug': typeof EventSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/dashboard/host': typeof AuthenticatedDashboardHostRouteWithChildren
  '/dashboard/judge': typeof AuthenticatedDashboardJudgeRouteWithChildren
  '/dashboard/participant': typeof AuthenticatedDashboardParticipantRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/attender/history': typeof AuthenticatedDashboardAttenderHistoryRoute
  '/dashboard/attender/scan': typeof AuthenticatedDashboardAttenderScanRoute
  '/dashboard/host/guide': typeof AuthenticatedDashboardHostGuideRoute
  '/event/$slug/submit': typeof AuthenticatedEventSlugSubmitRoute
  '/dashboard/attender': typeof AuthenticatedDashboardAttenderIndexRoute
  '/event/$slug/form/register': typeof AuthenticatedEventSlugFormRegisterRoute
  '/dashboard/host/events/$id/analytics': typeof AuthenticatedDashboardHostEventsIdAnalyticsRoute
  '/dashboard/host/events/$id/announcements': typeof AuthenticatedDashboardHostEventsIdAnnouncementsRoute
  '/dashboard/host/events/$id/attenders': typeof AuthenticatedDashboardHostEventsIdAttendersRoute
  '/dashboard/host/events/$id/form': typeof AuthenticatedDashboardHostEventsIdFormRoute
  '/dashboard/host/events/$id/judges': typeof AuthenticatedDashboardHostEventsIdJudgesRoute
  '/dashboard/host/events/$id/registrations': typeof AuthenticatedDashboardHostEventsIdRegistrationsRoute
  '/dashboard/host/events/$id/schedule': typeof AuthenticatedDashboardHostEventsIdScheduleRoute
  '/dashboard/host/events/$id/scores': typeof AuthenticatedDashboardHostEventsIdScoresRoute
  '/dashboard/host/events/$id/settings': typeof AuthenticatedDashboardHostEventsIdSettingsRoute
  '/dashboard/host/events/$id/submissions': typeof AuthenticatedDashboardHostEventsIdSubmissionsRoute
  '/dashboard/host/events/$id/website': typeof AuthenticatedDashboardHostEventsIdWebsiteRoute
  '/dashboard/judge/events/$eventId/schedule': typeof AuthenticatedDashboardJudgeEventsEventIdScheduleRoute
  '/dashboard/participant/events/$eventId/announcements': typeof AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute
  '/dashboard/participant/events/$eventId/info': typeof AuthenticatedDashboardParticipantEventsEventIdInfoRoute
  '/dashboard/participant/events/$eventId/schedule': typeof AuthenticatedDashboardParticipantEventsEventIdScheduleRoute
  '/dashboard/participant/events/$eventId/submissions': typeof AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute
  '/dashboard/participant/events/$eventId/team': typeof AuthenticatedDashboardParticipantEventsEventIdTeamRoute
  '/dashboard/host/events/$id': typeof AuthenticatedDashboardHostEventsIdIndexRoute
  '/dashboard/judge/events/$eventId/submissions/$submissionId': typeof AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/auth/attender': typeof AuthAttenderRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/host': typeof AuthHostRoute
  '/auth/judge': typeof AuthJudgeRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/event/$slug': typeof EventSlugRoute
  '/events/create': typeof EventsCreateRoute
  '/_authenticated/dashboard/attender': typeof AuthenticatedDashboardAttenderRouteWithChildren
  '/_authenticated/dashboard/host': typeof AuthenticatedDashboardHostRouteWithChildren
  '/_authenticated/dashboard/judge': typeof AuthenticatedDashboardJudgeRouteWithChildren
  '/_authenticated/dashboard/participant': typeof AuthenticatedDashboardParticipantRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/attender/history': typeof AuthenticatedDashboardAttenderHistoryRoute
  '/_authenticated/dashboard/attender/scan': typeof AuthenticatedDashboardAttenderScanRoute
  '/_authenticated/dashboard/host/guide': typeof AuthenticatedDashboardHostGuideRoute
  '/_authenticated/event/$slug/submit': typeof AuthenticatedEventSlugSubmitRoute
  '/_authenticated/dashboard/attender/': typeof AuthenticatedDashboardAttenderIndexRoute
  '/_authenticated/dashboard/host/events/$id': typeof AuthenticatedDashboardHostEventsIdRouteWithChildren
  '/_authenticated/event/$slug/form/register': typeof AuthenticatedEventSlugFormRegisterRoute
  '/_authenticated/dashboard/host/events/$id/analytics': typeof AuthenticatedDashboardHostEventsIdAnalyticsRoute
  '/_authenticated/dashboard/host/events/$id/announcements': typeof AuthenticatedDashboardHostEventsIdAnnouncementsRoute
  '/_authenticated/dashboard/host/events/$id/attenders': typeof AuthenticatedDashboardHostEventsIdAttendersRoute
  '/_authenticated/dashboard/host/events/$id/form': typeof AuthenticatedDashboardHostEventsIdFormRoute
  '/_authenticated/dashboard/host/events/$id/judges': typeof AuthenticatedDashboardHostEventsIdJudgesRoute
  '/_authenticated/dashboard/host/events/$id/registrations': typeof AuthenticatedDashboardHostEventsIdRegistrationsRoute
  '/_authenticated/dashboard/host/events/$id/schedule': typeof AuthenticatedDashboardHostEventsIdScheduleRoute
  '/_authenticated/dashboard/host/events/$id/scores': typeof AuthenticatedDashboardHostEventsIdScoresRoute
  '/_authenticated/dashboard/host/events/$id/settings': typeof AuthenticatedDashboardHostEventsIdSettingsRoute
  '/_authenticated/dashboard/host/events/$id/submissions': typeof AuthenticatedDashboardHostEventsIdSubmissionsRoute
  '/_authenticated/dashboard/host/events/$id/website': typeof AuthenticatedDashboardHostEventsIdWebsiteRoute
  '/_authenticated/dashboard/judge/events/$eventId/schedule': typeof AuthenticatedDashboardJudgeEventsEventIdScheduleRoute
  '/_authenticated/dashboard/participant/events/$eventId/announcements': typeof AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute
  '/_authenticated/dashboard/participant/events/$eventId/info': typeof AuthenticatedDashboardParticipantEventsEventIdInfoRoute
  '/_authenticated/dashboard/participant/events/$eventId/schedule': typeof AuthenticatedDashboardParticipantEventsEventIdScheduleRoute
  '/_authenticated/dashboard/participant/events/$eventId/submissions': typeof AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute
  '/_authenticated/dashboard/participant/events/$eventId/team': typeof AuthenticatedDashboardParticipantEventsEventIdTeamRoute
  '/_authenticated/dashboard/host/events/$id/': typeof AuthenticatedDashboardHostEventsIdIndexRoute
  '/_authenticated/dashboard/judge/events/$eventId/submissions/$submissionId': typeof AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/auth/attender'
    | '/auth/forgot'
    | '/auth/host'
    | '/auth/judge'
    | '/auth/participant'
    | '/event/$slug'
    | '/events/create'
    | '/dashboard/attender'
    | '/dashboard/host'
    | '/dashboard/judge'
    | '/dashboard/participant'
    | '/dashboard/settings'
    | '/dashboard/attender/history'
    | '/dashboard/attender/scan'
    | '/dashboard/host/guide'
    | '/event/$slug/submit'
    | '/dashboard/attender/'
    | '/dashboard/host/events/$id'
    | '/event/$slug/form/register'
    | '/dashboard/host/events/$id/analytics'
    | '/dashboard/host/events/$id/announcements'
    | '/dashboard/host/events/$id/attenders'
    | '/dashboard/host/events/$id/form'
    | '/dashboard/host/events/$id/judges'
    | '/dashboard/host/events/$id/registrations'
    | '/dashboard/host/events/$id/schedule'
    | '/dashboard/host/events/$id/scores'
    | '/dashboard/host/events/$id/settings'
    | '/dashboard/host/events/$id/submissions'
    | '/dashboard/host/events/$id/website'
    | '/dashboard/judge/events/$eventId/schedule'
    | '/dashboard/participant/events/$eventId/announcements'
    | '/dashboard/participant/events/$eventId/info'
    | '/dashboard/participant/events/$eventId/schedule'
    | '/dashboard/participant/events/$eventId/submissions'
    | '/dashboard/participant/events/$eventId/team'
    | '/dashboard/host/events/$id/'
    | '/dashboard/judge/events/$eventId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/auth/attender'
    | '/auth/forgot'
    | '/auth/host'
    | '/auth/judge'
    | '/auth/participant'
    | '/event/$slug'
    | '/events/create'
    | '/dashboard/host'
    | '/dashboard/judge'
    | '/dashboard/participant'
    | '/dashboard/settings'
    | '/dashboard/attender/history'
    | '/dashboard/attender/scan'
    | '/dashboard/host/guide'
    | '/event/$slug/submit'
    | '/dashboard/attender'
    | '/event/$slug/form/register'
    | '/dashboard/host/events/$id/analytics'
    | '/dashboard/host/events/$id/announcements'
    | '/dashboard/host/events/$id/attenders'
    | '/dashboard/host/events/$id/form'
    | '/dashboard/host/events/$id/judges'
    | '/dashboard/host/events/$id/registrations'
    | '/dashboard/host/events/$id/schedule'
    | '/dashboard/host/events/$id/scores'
    | '/dashboard/host/events/$id/settings'
    | '/dashboard/host/events/$id/submissions'
    | '/dashboard/host/events/$id/website'
    | '/dashboard/judge/events/$eventId/schedule'
    | '/dashboard/participant/events/$eventId/announcements'
    | '/dashboard/participant/events/$eventId/info'
    | '/dashboard/participant/events/$eventId/schedule'
    | '/dashboard/participant/events/$eventId/submissions'
    | '/dashboard/participant/events/$eventId/team'
    | '/dashboard/host/events/$id'
    | '/dashboard/judge/events/$eventId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/auth/attender'
    | '/auth/forgot'
    | '/auth/host'
    | '/auth/judge'
    | '/auth/participant'
    | '/event/$slug'
    | '/events/create'
    | '/_authenticated/dashboard/attender'
    | '/_authenticated/dashboard/host'
    | '/_authenticated/dashboard/judge'
    | '/_authenticated/dashboard/participant'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/attender/history'
    | '/_authenticated/dashboard/attender/scan'
    | '/_authenticated/dashboard/host/guide'
    | '/_authenticated/event/$slug/submit'
    | '/_authenticated/dashboard/attender/'
    | '/_authenticated/dashboard/host/events/$id'
    | '/_authenticated/event/$slug/form/register'
    | '/_authenticated/dashboard/host/events/$id/analytics'
    | '/_authenticated/dashboard/host/events/$id/announcements'
    | '/_authenticated/dashboard/host/events/$id/attenders'
    | '/_authenticated/dashboard/host/events/$id/form'
    | '/_authenticated/dashboard/host/events/$id/judges'
    | '/_authenticated/dashboard/host/events/$id/registrations'
    | '/_authenticated/dashboard/host/events/$id/schedule'
    | '/_authenticated/dashboard/host/events/$id/scores'
    | '/_authenticated/dashboard/host/events/$id/settings'
    | '/_authenticated/dashboard/host/events/$id/submissions'
    | '/_authenticated/dashboard/host/events/$id/website'
    | '/_authenticated/dashboard/judge/events/$eventId/schedule'
    | '/_authenticated/dashboard/participant/events/$eventId/announcements'
    | '/_authenticated/dashboard/participant/events/$eventId/info'
    | '/_authenticated/dashboard/participant/events/$eventId/schedule'
    | '/_authenticated/dashboard/participant/events/$eventId/submissions'
    | '/_authenticated/dashboard/participant/events/$eventId/team'
    | '/_authenticated/dashboard/host/events/$id/'
    | '/_authenticated/dashboard/judge/events/$eventId/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthAttenderRoute: typeof AuthAttenderRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthHostRoute: typeof AuthHostRoute
  AuthJudgeRoute: typeof AuthJudgeRoute
  AuthParticipantRoute: typeof AuthParticipantRoute
  EventSlugRoute: typeof EventSlugRoute
  EventsCreateRoute: typeof EventsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/participant': {
      id: '/auth/participant'
      path: '/auth/participant'
      fullPath: '/auth/participant'
      preLoaderRoute: typeof AuthParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/judge': {
      id: '/auth/judge'
      path: '/auth/judge'
      fullPath: '/auth/judge'
      preLoaderRoute: typeof AuthJudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/host': {
      id: '/auth/host'
      path: '/auth/host'
      fullPath: '/auth/host'
      preLoaderRoute: typeof AuthHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/attender': {
      id: '/auth/attender'
      path: '/auth/attender'
      fullPath: '/auth/attender'
      preLoaderRoute: typeof AuthAttenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/participant': {
      id: '/_authenticated/dashboard/participant'
      path: '/dashboard/participant'
      fullPath: '/dashboard/participant'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/judge': {
      id: '/_authenticated/dashboard/judge'
      path: '/dashboard/judge'
      fullPath: '/dashboard/judge'
      preLoaderRoute: typeof AuthenticatedDashboardJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/host': {
      id: '/_authenticated/dashboard/host'
      path: '/dashboard/host'
      fullPath: '/dashboard/host'
      preLoaderRoute: typeof AuthenticatedDashboardHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/attender': {
      id: '/_authenticated/dashboard/attender'
      path: '/dashboard/attender'
      fullPath: '/dashboard/attender'
      preLoaderRoute: typeof AuthenticatedDashboardAttenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/attender/': {
      id: '/_authenticated/dashboard/attender/'
      path: '/'
      fullPath: '/dashboard/attender/'
      preLoaderRoute: typeof AuthenticatedDashboardAttenderIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAttenderRoute
    }
    '/_authenticated/event/$slug/submit': {
      id: '/_authenticated/event/$slug/submit'
      path: '/event/$slug/submit'
      fullPath: '/event/$slug/submit'
      preLoaderRoute: typeof AuthenticatedEventSlugSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/host/guide': {
      id: '/_authenticated/dashboard/host/guide'
      path: '/guide'
      fullPath: '/dashboard/host/guide'
      preLoaderRoute: typeof AuthenticatedDashboardHostGuideRouteImport
      parentRoute: typeof AuthenticatedDashboardHostRoute
    }
    '/_authenticated/dashboard/attender/scan': {
      id: '/_authenticated/dashboard/attender/scan'
      path: '/scan'
      fullPath: '/dashboard/attender/scan'
      preLoaderRoute: typeof AuthenticatedDashboardAttenderScanRouteImport
      parentRoute: typeof AuthenticatedDashboardAttenderRoute
    }
    '/_authenticated/dashboard/attender/history': {
      id: '/_authenticated/dashboard/attender/history'
      path: '/history'
      fullPath: '/dashboard/attender/history'
      preLoaderRoute: typeof AuthenticatedDashboardAttenderHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardAttenderRoute
    }
    '/_authenticated/event/$slug/form/register': {
      id: '/_authenticated/event/$slug/form/register'
      path: '/event/$slug/form/register'
      fullPath: '/event/$slug/form/register'
      preLoaderRoute: typeof AuthenticatedEventSlugFormRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/host/events/$id': {
      id: '/_authenticated/dashboard/host/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/host/events/$id'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardHostRoute
    }
    '/_authenticated/dashboard/host/events/$id/': {
      id: '/_authenticated/dashboard/host/events/$id/'
      path: '/'
      fullPath: '/dashboard/host/events/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/participant/events/$eventId/team': {
      id: '/_authenticated/dashboard/participant/events/$eventId/team'
      path: '/events/$eventId/team'
      fullPath: '/dashboard/participant/events/$eventId/team'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantEventsEventIdTeamRouteImport
      parentRoute: typeof AuthenticatedDashboardParticipantRoute
    }
    '/_authenticated/dashboard/participant/events/$eventId/submissions': {
      id: '/_authenticated/dashboard/participant/events/$eventId/submissions'
      path: '/events/$eventId/submissions'
      fullPath: '/dashboard/participant/events/$eventId/submissions'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantEventsEventIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardParticipantRoute
    }
    '/_authenticated/dashboard/participant/events/$eventId/schedule': {
      id: '/_authenticated/dashboard/participant/events/$eventId/schedule'
      path: '/events/$eventId/schedule'
      fullPath: '/dashboard/participant/events/$eventId/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantEventsEventIdScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardParticipantRoute
    }
    '/_authenticated/dashboard/participant/events/$eventId/info': {
      id: '/_authenticated/dashboard/participant/events/$eventId/info'
      path: '/events/$eventId/info'
      fullPath: '/dashboard/participant/events/$eventId/info'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantEventsEventIdInfoRouteImport
      parentRoute: typeof AuthenticatedDashboardParticipantRoute
    }
    '/_authenticated/dashboard/participant/events/$eventId/announcements': {
      id: '/_authenticated/dashboard/participant/events/$eventId/announcements'
      path: '/events/$eventId/announcements'
      fullPath: '/dashboard/participant/events/$eventId/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardParticipantRoute
    }
    '/_authenticated/dashboard/judge/events/$eventId/schedule': {
      id: '/_authenticated/dashboard/judge/events/$eventId/schedule'
      path: '/events/$eventId/schedule'
      fullPath: '/dashboard/judge/events/$eventId/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardJudgeEventsEventIdScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardJudgeRoute
    }
    '/_authenticated/dashboard/host/events/$id/website': {
      id: '/_authenticated/dashboard/host/events/$id/website'
      path: '/website'
      fullPath: '/dashboard/host/events/$id/website'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdWebsiteRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/submissions': {
      id: '/_authenticated/dashboard/host/events/$id/submissions'
      path: '/submissions'
      fullPath: '/dashboard/host/events/$id/submissions'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/settings': {
      id: '/_authenticated/dashboard/host/events/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/host/events/$id/settings'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/scores': {
      id: '/_authenticated/dashboard/host/events/$id/scores'
      path: '/scores'
      fullPath: '/dashboard/host/events/$id/scores'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdScoresRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/schedule': {
      id: '/_authenticated/dashboard/host/events/$id/schedule'
      path: '/schedule'
      fullPath: '/dashboard/host/events/$id/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/registrations': {
      id: '/_authenticated/dashboard/host/events/$id/registrations'
      path: '/registrations'
      fullPath: '/dashboard/host/events/$id/registrations'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/judges': {
      id: '/_authenticated/dashboard/host/events/$id/judges'
      path: '/judges'
      fullPath: '/dashboard/host/events/$id/judges'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdJudgesRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/form': {
      id: '/_authenticated/dashboard/host/events/$id/form'
      path: '/form'
      fullPath: '/dashboard/host/events/$id/form'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdFormRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/attenders': {
      id: '/_authenticated/dashboard/host/events/$id/attenders'
      path: '/attenders'
      fullPath: '/dashboard/host/events/$id/attenders'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdAttendersRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/announcements': {
      id: '/_authenticated/dashboard/host/events/$id/announcements'
      path: '/announcements'
      fullPath: '/dashboard/host/events/$id/announcements'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/host/events/$id/analytics': {
      id: '/_authenticated/dashboard/host/events/$id/analytics'
      path: '/analytics'
      fullPath: '/dashboard/host/events/$id/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardHostEventsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardHostEventsIdRoute
    }
    '/_authenticated/dashboard/judge/events/$eventId/submissions/$submissionId': {
      id: '/_authenticated/dashboard/judge/events/$eventId/submissions/$submissionId'
      path: '/events/$eventId/submissions/$submissionId'
      fullPath: '/dashboard/judge/events/$eventId/submissions/$submissionId'
      preLoaderRoute: typeof AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardJudgeRoute
    }
  }
}

interface AuthenticatedDashboardAttenderRouteChildren {
  AuthenticatedDashboardAttenderHistoryRoute: typeof AuthenticatedDashboardAttenderHistoryRoute
  AuthenticatedDashboardAttenderScanRoute: typeof AuthenticatedDashboardAttenderScanRoute
  AuthenticatedDashboardAttenderIndexRoute: typeof AuthenticatedDashboardAttenderIndexRoute
}

const AuthenticatedDashboardAttenderRouteChildren: AuthenticatedDashboardAttenderRouteChildren =
  {
    AuthenticatedDashboardAttenderHistoryRoute:
      AuthenticatedDashboardAttenderHistoryRoute,
    AuthenticatedDashboardAttenderScanRoute:
      AuthenticatedDashboardAttenderScanRoute,
    AuthenticatedDashboardAttenderIndexRoute:
      AuthenticatedDashboardAttenderIndexRoute,
  }

const AuthenticatedDashboardAttenderRouteWithChildren =
  AuthenticatedDashboardAttenderRoute._addFileChildren(
    AuthenticatedDashboardAttenderRouteChildren,
  )

interface AuthenticatedDashboardHostEventsIdRouteChildren {
  AuthenticatedDashboardHostEventsIdAnalyticsRoute: typeof AuthenticatedDashboardHostEventsIdAnalyticsRoute
  AuthenticatedDashboardHostEventsIdAnnouncementsRoute: typeof AuthenticatedDashboardHostEventsIdAnnouncementsRoute
  AuthenticatedDashboardHostEventsIdAttendersRoute: typeof AuthenticatedDashboardHostEventsIdAttendersRoute
  AuthenticatedDashboardHostEventsIdFormRoute: typeof AuthenticatedDashboardHostEventsIdFormRoute
  AuthenticatedDashboardHostEventsIdJudgesRoute: typeof AuthenticatedDashboardHostEventsIdJudgesRoute
  AuthenticatedDashboardHostEventsIdRegistrationsRoute: typeof AuthenticatedDashboardHostEventsIdRegistrationsRoute
  AuthenticatedDashboardHostEventsIdScheduleRoute: typeof AuthenticatedDashboardHostEventsIdScheduleRoute
  AuthenticatedDashboardHostEventsIdScoresRoute: typeof AuthenticatedDashboardHostEventsIdScoresRoute
  AuthenticatedDashboardHostEventsIdSettingsRoute: typeof AuthenticatedDashboardHostEventsIdSettingsRoute
  AuthenticatedDashboardHostEventsIdSubmissionsRoute: typeof AuthenticatedDashboardHostEventsIdSubmissionsRoute
  AuthenticatedDashboardHostEventsIdWebsiteRoute: typeof AuthenticatedDashboardHostEventsIdWebsiteRoute
  AuthenticatedDashboardHostEventsIdIndexRoute: typeof AuthenticatedDashboardHostEventsIdIndexRoute
}

const AuthenticatedDashboardHostEventsIdRouteChildren: AuthenticatedDashboardHostEventsIdRouteChildren =
  {
    AuthenticatedDashboardHostEventsIdAnalyticsRoute:
      AuthenticatedDashboardHostEventsIdAnalyticsRoute,
    AuthenticatedDashboardHostEventsIdAnnouncementsRoute:
      AuthenticatedDashboardHostEventsIdAnnouncementsRoute,
    AuthenticatedDashboardHostEventsIdAttendersRoute:
      AuthenticatedDashboardHostEventsIdAttendersRoute,
    AuthenticatedDashboardHostEventsIdFormRoute:
      AuthenticatedDashboardHostEventsIdFormRoute,
    AuthenticatedDashboardHostEventsIdJudgesRoute:
      AuthenticatedDashboardHostEventsIdJudgesRoute,
    AuthenticatedDashboardHostEventsIdRegistrationsRoute:
      AuthenticatedDashboardHostEventsIdRegistrationsRoute,
    AuthenticatedDashboardHostEventsIdScheduleRoute:
      AuthenticatedDashboardHostEventsIdScheduleRoute,
    AuthenticatedDashboardHostEventsIdScoresRoute:
      AuthenticatedDashboardHostEventsIdScoresRoute,
    AuthenticatedDashboardHostEventsIdSettingsRoute:
      AuthenticatedDashboardHostEventsIdSettingsRoute,
    AuthenticatedDashboardHostEventsIdSubmissionsRoute:
      AuthenticatedDashboardHostEventsIdSubmissionsRoute,
    AuthenticatedDashboardHostEventsIdWebsiteRoute:
      AuthenticatedDashboardHostEventsIdWebsiteRoute,
    AuthenticatedDashboardHostEventsIdIndexRoute:
      AuthenticatedDashboardHostEventsIdIndexRoute,
  }

const AuthenticatedDashboardHostEventsIdRouteWithChildren =
  AuthenticatedDashboardHostEventsIdRoute._addFileChildren(
    AuthenticatedDashboardHostEventsIdRouteChildren,
  )

interface AuthenticatedDashboardHostRouteChildren {
  AuthenticatedDashboardHostGuideRoute: typeof AuthenticatedDashboardHostGuideRoute
  AuthenticatedDashboardHostEventsIdRoute: typeof AuthenticatedDashboardHostEventsIdRouteWithChildren
}

const AuthenticatedDashboardHostRouteChildren: AuthenticatedDashboardHostRouteChildren =
  {
    AuthenticatedDashboardHostGuideRoute: AuthenticatedDashboardHostGuideRoute,
    AuthenticatedDashboardHostEventsIdRoute:
      AuthenticatedDashboardHostEventsIdRouteWithChildren,
  }

const AuthenticatedDashboardHostRouteWithChildren =
  AuthenticatedDashboardHostRoute._addFileChildren(
    AuthenticatedDashboardHostRouteChildren,
  )

interface AuthenticatedDashboardJudgeRouteChildren {
  AuthenticatedDashboardJudgeEventsEventIdScheduleRoute: typeof AuthenticatedDashboardJudgeEventsEventIdScheduleRoute
  AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute: typeof AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute
}

const AuthenticatedDashboardJudgeRouteChildren: AuthenticatedDashboardJudgeRouteChildren =
  {
    AuthenticatedDashboardJudgeEventsEventIdScheduleRoute:
      AuthenticatedDashboardJudgeEventsEventIdScheduleRoute,
    AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute:
      AuthenticatedDashboardJudgeEventsEventIdSubmissionsSubmissionIdRoute,
  }

const AuthenticatedDashboardJudgeRouteWithChildren =
  AuthenticatedDashboardJudgeRoute._addFileChildren(
    AuthenticatedDashboardJudgeRouteChildren,
  )

interface AuthenticatedDashboardParticipantRouteChildren {
  AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute: typeof AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute
  AuthenticatedDashboardParticipantEventsEventIdInfoRoute: typeof AuthenticatedDashboardParticipantEventsEventIdInfoRoute
  AuthenticatedDashboardParticipantEventsEventIdScheduleRoute: typeof AuthenticatedDashboardParticipantEventsEventIdScheduleRoute
  AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute: typeof AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute
  AuthenticatedDashboardParticipantEventsEventIdTeamRoute: typeof AuthenticatedDashboardParticipantEventsEventIdTeamRoute
}

const AuthenticatedDashboardParticipantRouteChildren: AuthenticatedDashboardParticipantRouteChildren =
  {
    AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute:
      AuthenticatedDashboardParticipantEventsEventIdAnnouncementsRoute,
    AuthenticatedDashboardParticipantEventsEventIdInfoRoute:
      AuthenticatedDashboardParticipantEventsEventIdInfoRoute,
    AuthenticatedDashboardParticipantEventsEventIdScheduleRoute:
      AuthenticatedDashboardParticipantEventsEventIdScheduleRoute,
    AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute:
      AuthenticatedDashboardParticipantEventsEventIdSubmissionsRoute,
    AuthenticatedDashboardParticipantEventsEventIdTeamRoute:
      AuthenticatedDashboardParticipantEventsEventIdTeamRoute,
  }

const AuthenticatedDashboardParticipantRouteWithChildren =
  AuthenticatedDashboardParticipantRoute._addFileChildren(
    AuthenticatedDashboardParticipantRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAttenderRoute: typeof AuthenticatedDashboardAttenderRouteWithChildren
  AuthenticatedDashboardHostRoute: typeof AuthenticatedDashboardHostRouteWithChildren
  AuthenticatedDashboardJudgeRoute: typeof AuthenticatedDashboardJudgeRouteWithChildren
  AuthenticatedDashboardParticipantRoute: typeof AuthenticatedDashboardParticipantRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedEventSlugSubmitRoute: typeof AuthenticatedEventSlugSubmitRoute
  AuthenticatedEventSlugFormRegisterRoute: typeof AuthenticatedEventSlugFormRegisterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAttenderRoute:
    AuthenticatedDashboardAttenderRouteWithChildren,
  AuthenticatedDashboardHostRoute: AuthenticatedDashboardHostRouteWithChildren,
  AuthenticatedDashboardJudgeRoute:
    AuthenticatedDashboardJudgeRouteWithChildren,
  AuthenticatedDashboardParticipantRoute:
    AuthenticatedDashboardParticipantRouteWithChildren,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedEventSlugSubmitRoute: AuthenticatedEventSlugSubmitRoute,
  AuthenticatedEventSlugFormRegisterRoute:
    AuthenticatedEventSlugFormRegisterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthAttenderRoute: AuthAttenderRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthHostRoute: AuthHostRoute,
  AuthJudgeRoute: AuthJudgeRoute,
  AuthParticipantRoute: AuthParticipantRoute,
  EventSlugRoute: EventSlugRoute,
  EventsCreateRoute: EventsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
